# Generated by Django 2.0.5 on 2018-09-14 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180914_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 23, 10, 21, 15907, tzinfo=utc)),
        ),
    ]
