# Generated by Django 2.0.5 on 2018-09-16 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20180914_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 1, 34, 27, 541570, tzinfo=utc)),
        ),
    ]
