# Generated by Django 2.0.5 on 2018-09-16 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180915_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 1, 37, 57, 21274, tzinfo=utc)),
        ),
    ]
