# Generated by Django 2.0.5 on 2018-09-24 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20180916_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 0, 28, 51, 19006, tzinfo=utc)),
        ),
    ]
