# Generated by Django 2.0.5 on 2018-09-24 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20180923_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 3, 15, 38, 817156, tzinfo=utc)),
        ),
    ]
